@echo off
echo Initializing Git repository...
git init
echo Adding all files...
git add .
echo Committing changes...
git commit -m "Initial commit of photo gallery website"
echo Adding remote origin...
git remote add origin https://github.com/Rooland1/FotoGaleria.git
echo Pushing to GitHub...
git push -u origin main
echo Done!
pause
